[package]
name = "sealing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring-compat = "0.6.0"
zeroize = { version = "1.5.7", features = ["derive"] }
