name: "Run TODO to Issue"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "TODO to Issue"
        # https://github.com/marketplace/actions/todo-to-issue
        uses: "alstr/todo-to-issue-action@v4"
